spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true # /h2-console 설정
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:bottle_kill # 메모리 H2 DB 경로 설정